# Generated by Django 3.2.3 on 2021-05-20 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie_title_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_left', to='community.movie')),
                ('movie_title_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_right', to='community.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote_users', models.ManyToManyField(related_name='vote_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
